#!/bin/bash

# Fix SSH auth socket location so agent forwarding works with tmux
# check https://stackoverflow.com/a/23187030 for details

if test "$SSH_AUTH_SOCK" ; then
  ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
