#!/bin/bash

function get_pwd () {

 	# find directory of this script
	SOURCE="${BASH_SOURCE[0]}"
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
    	DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
		SOURCE="$(readlink "$SOURCE")"
     	[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to      resolve it relative to the path where the symlink file was located
 	done
	DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null && pwd )"
	echo "$DIR"
}

function graceful_ln () {
	if [ -e $2 ]
	then
		# symlink/file already exists
		echo "symlink from $2 to $1 already exists, delete first"
	else
		ln -s $1 $2
	fi
}
